
discovery:
  server:
    port: 8070
    hostName: 18.220.102.31

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${discovery.server.hostName}:${discovery.server.port}/eureka'
    region: us-east-2
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    ip-address: 18.220.102.31
    hostname: 18.220.102.31
    #non-secure-port: 9096

logging:
  file:
    name: '/home/ubuntu/reader-logs/reader-app-prod.log'
  level:
    root: info

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'

database:
  host: '3.18.118.202'
  port: 3306
  db-name: dailyreader


spring:
  datasource:
    url: 'jdbc:mysql://${database.host}:${database.port}/${database.db-name}?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
    username: root
    password: 14292Celebs
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: false
      validation-query: SELECT 1
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 3.18.118.202
    port: 6969
  cache:
    cache-names: READER
    redis:
      time-to-live: 120000