
management:
 endpoint:
  shutdown:
   enabled: true
 endpoints:
  web:
   exposure:
    include:
     - '*'

database:
 host: '3.134.205.70'
 port: 3306
 db-name: dailyreader

spring:
 datasource:
  url: 'jdbc:mysql://${database.host}:${database.port}/${database.db-name}?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false'
  username: root
  password: 14292Celebs
  driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
   test-while-idle: false
   validation-query: SELECT 1
 sql:
  init:
   mode: always
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
  hibernate:
   ddl-auto: update